spring.datasource.url=jdbc:postgresql://ep-late-poetry-acyplzzc-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Ht4VrweGpWN8
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2s
spring.data.redis.connect-timeout=2s
# Mostra hit/miss do cache no console
logging.level.org.springframework.cache=TRACE

# Remove aquele monte de INFO "Could not safely identify store assignment..."
spring.data.redis.repositories.enabled=false

server.port=8080


# Iniciar o docker ( docker compose up -d )

# Encerrar ( docker compose down )