DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

GRANT USAGE ON SCHEMA public TO anon, authenticated;


CREATE TABLE "tb_usuario" (
                              "id_usuario" uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
                              "nome" varchar(100) NOT NULL,
                              "email" varchar(100) NOT NULL UNIQUE,
                              "senha" varchar(255),
                              "data_nascimento" date,
                              "cargo" varchar(20) NOT NULL DEFAULT 'CLIENTE' CHECK (cargo IN ('CLIENTE', 'ADMIN'))
);

CREATE TABLE "tb_conteudo" (
                               "id_conteudo" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                               "titulo" varchar(255) NOT NULL,
                               "descricao" text,
                               "tipo" varchar(50),
                               "id_usuario" uuid REFERENCES "tb_usuario"("id_usuario") ON DELETE SET NULL
);

CREATE TABLE "tb_filme" (
                            "id_conteudo" bigint PRIMARY KEY REFERENCES "tb_conteudo"("id_conteudo") ON DELETE CASCADE,
                            "url_filme" varchar(255),
                            "duracao_minutos" integer
);

CREATE TABLE "tb_serie" (
                            "id_conteudo" bigint PRIMARY KEY REFERENCES "tb_conteudo"("id_conteudo") ON DELETE CASCADE
);

CREATE TABLE "tb_temporada" (
                                "id_temporada" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                "numero_temporada" integer NOT NULL,
                                "id_serie" bigint REFERENCES "tb_serie"("id_conteudo") ON DELETE CASCADE
);

CREATE TABLE "tb_episodio" (
                               "id_episodio" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                               "nome_episodio" varchar(255),
                               "numero_episodio" integer,
                               "duracao_minutos" integer,
                               "url_episodio" varchar(255),
                               "id_temporada" bigint REFERENCES "tb_temporada"("id_temporada") ON DELETE CASCADE
);

CREATE TABLE "tb_genero" (
                             "id_genero" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                             "nome" varchar(255) NOT NULL UNIQUE,
                             "descricao" varchar(255)
);

CREATE TABLE "tb_conteudo_genero" (
                                      "id_conteudo" bigint REFERENCES "tb_conteudo"("id_conteudo") ON DELETE CASCADE,
                                      "id_genero" bigint REFERENCES "tb_genero"("id_genero") ON DELETE CASCADE,
                                      PRIMARY KEY ("id_conteudo", "id_genero")
);

CREATE TABLE "tb_plano" (
                            "id_assinatura" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "tipo_plano" varchar(50) NOT NULL CHECK (tipo_plano IN ('BASICO', 'PADRAO', 'PREMIUM')),
                            "valor" numeric(10, 2) NOT NULL
);

CREATE TABLE "tb_assinatura" (
                                 "id_assinatura" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                 "data_inicio" date,
                                 "data_fim" date,
                                 "status" varchar(50),
                                 "id_plano" bigint REFERENCES "tb_plano"("id_assinatura"),
                                 "id_usuario" uuid REFERENCES "tb_usuario"("id_usuario") ON DELETE CASCADE
);

CREATE TABLE "tb_avaliacao" (
                                "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                "nota" double precision,
                                "id_conteudo" bigint REFERENCES "tb_conteudo"("id_conteudo") ON DELETE CASCADE,
                                "id_usuario" uuid REFERENCES "tb_usuario"("id_usuario") ON DELETE CASCADE
);

CREATE TABLE "tb_historico" (
                                "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                "timestamp" timestamp,
                                "id_conteudo" bigint REFERENCES "tb_conteudo"("id_conteudo") ON DELETE CASCADE,
                                "id_usuario" uuid REFERENCES "tb_usuario"("id_usuario") ON DELETE CASCADE
);

CREATE TABLE "tb_lista_desejo" (
                                   "id_lista" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                   "nome" varchar(255) NOT NULL,
                                   "data_criacao" timestamp,
                                   "id_usuario" uuid REFERENCES "tb_usuario"("id_usuario") ON DELETE CASCADE
);

CREATE TABLE "tb_lista_conteudo" (
                                     "id_lista" bigint REFERENCES "tb_lista_desejo"("id_lista") ON DELETE CASCADE,
                                     "id_conteudo" bigint REFERENCES "tb_conteudo"("id_conteudo") ON DELETE CASCADE,
                                     PRIMARY KEY ("id_lista", "id_conteudo")
);

CREATE TABLE "tb_recomendacao" (
                                   "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                   "motivo" varchar(255),
                                   "id_conteudo" bigint REFERENCES "tb_conteudo"("id_conteudo") ON DELETE CASCADE,
                                   "id_usuario" uuid REFERENCES "tb_usuario"("id_usuario") ON DELETE CASCADE
);